### ISSUE TITLE
Add source problems

### ISSUE THREAD

**Issue by kdecks** [GameDragon2k/RASuite#10] opened 2018-02-10 04:27 UTC
It seems if you have a chain of add source reqs and a hit in the final one the value carries though into additional achievements.

Also if there are a large number of add source reqs (in my test ~30 with 2 groups of 15 added sources) having a delta/mem check on the two final addresses of the groups wasn't working when tested. Sorry if this is a bit vague, let me know if you need a clearer example.

**Comment by GameDragon2k** [comment] 2018-02-11 03:23
I'm still not able to recreate this. If you are able, can you reproduce this and give me steps on how to do it? Can you also reproduce it in a new local achievement?

**Comment by kdecks** [comment] 2018-02-11 04:21
I dumped a bunch and it repeats itself. Go to the bottom for the simplest config that isn't working.

![image](https://user-images.githubusercontent.com/32706333/36069354-1b600e42-0ea5-11e8-8829-c35fe1d2ccdf.png)
Here is my example. It When I have 4 medals condition 30 is getting hits, and then when I add a 5th condition 15 is getting hits, but the achievement isn't triggering.

![image](https://user-images.githubusercontent.com/32706333/36069380-99cb611e-0ea5-11e8-922c-1c7d4737b4d4.png)
This worked.

![image](https://user-images.githubusercontent.com/32706333/36069418-7b244cd4-0ea6-11e8-8e12-0a4d3c1eba31.png)
not working.

![image](https://user-images.githubusercontent.com/32706333/36069425-99d5b74e-0ea6-11e8-8fa1-e8610145ba10.png)
not working

![image](https://user-images.githubusercontent.com/32706333/36069431-bfa55c7c-0ea6-11e8-93cf-7cb1fed9b5fe.png)
not working

![image](https://user-images.githubusercontent.com/32706333/36069433-e6ad1d6e-0ea6-11e8-91ac-b39c82bc6433.png)

working

![image](https://user-images.githubusercontent.com/32706333/36069436-f9075eac-0ea6-11e8-8a9a-f1c1ebdc22ad.png)

working

![image](https://user-images.githubusercontent.com/32706333/36069498-409691ce-0ea8-11e8-8808-7735910f043d.png)

This is the simplest config that isn't working for me.

**Comment by GameDragon2k** [comment] 2018-02-11 04:54
What about the hit counter?

**Comment by GameDragon2k** [comment] 2018-02-11 05:20
I see what the issue is in regards to the delta. It's not really an *issue*, it's just a complicated logic.
Line 3 is only checking the delta of **0x16e6e3**. If you toggle both 0x16e6e0 and 0x16e6e1, the delta is still 0. Line 3 is not checking the delta of the previous addresses, just it's own.

What you actually want to do in this case is add the deltas of the previous addresses together like so:
![image](https://user-images.githubusercontent.com/3225327/36070021-b77e7168-0ec0-11e8-9de1-72625ca75baa.png)

**Comment by kdecks** [comment] 2018-02-11 05:29
Interesting config. You should post that on the wiki.

The hit counter is a separate issue. I should have split this into two problems. Anyway, I'll show you tomorrow.

**Comment by kdecks** [comment] 2018-02-13 03:37
Case 1:
![image](https://user-images.githubusercontent.com/32706333/36132364-09c7e4b2-1034-11e8-86c4-860d7480de72.png)
8 is a dummy condition to prevent unlock.
Conditions 1--4's values are true.
Once the hits in condition 5 are filled condition 6 begins to take active hits.

Case 2:
![image](https://user-images.githubusercontent.com/32706333/36132390-4089826c-1034-11e8-961b-7630c53ee3ff.png)
If hits are added to condition 6 condition 7 begins to take hits.
It's also important to note that in this example the value of conditions 7's address is 4 not 8 meaning the add hits values are carrying into 6 and 7.

**Comment by GameDragon2k** [comment] 2018-02-13 16:41
Wow, yeah this is an issue. This needs to be fixed in RetroArch too then.

**Comment by GameDragon2k** [comment] 2018-02-14 03:12
Fixed here and in RetroArch. Thanks.

**Closed as completed by GameDragon2k** 2018-02-14 03:12 UTC
